[package]
name = "brainfuck"
description = "A cli for brainfuck"
authors = ["Gio Genre De Asis"]
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
seahorse = "2.1"